# source: https://github.com/yidinghan/eak
version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    ports:
    - 9200:9200
    environment:
    - discovery.type=single-node
    volumes:
    - esdata:/usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    ports:
    - 5601:5601
    environment:
    - output.elasticsearch.hosts=['http://elasticsearch:9200']
    depends_on:
    - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.3.1
    ports:
    - 8200:8200
    environment:
    - output.elasticsearch.hosts=['http://elasticsearch:9200']
    - apm-server.host="0.0.0.0:8200"
    - apm-server.secret_token=""
    - setup.kibana.host="kibana:5601"
    - setup.template.enabled=true
    - logging.to_files=false
    depends_on:
    - elasticsearch

  
volumes:
  esdata:
    driver: local